const mongoose = require('mongoose');
const dotenv = require('dotenv');
const Product = require('./models/Product');
const User = require('./models/User');

dotenv.config({ path: './.env' });

const sampleProducts = [
  // Men Category - 10 Products
  {
    name: 'Classic Cotton T-Shirt',
    description: 'Premium quality cotton t-shirt perfect for casual wear. Soft, breathable, and comfortable.',
    price: 499,
    originalPrice: 799,
    category: 'Men',
    subcategory: 'T-Shirts',
    brand: 'FashionHub',
    images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500'],
    stock: 50,
    ratings: { average: 4.2, count: 25 },
    tags: ['casual', 'cotton', 'summer'],
    isFeatured: true
  },
  {
    name: 'Slim Fit Jeans',
    description: 'Modern slim fit jeans with stretch fabric. Perfect for everyday wear.',
    price: 1299,
    originalPrice: 1999,
    category: 'Men',
    subcategory: 'Jeans',
    brand: 'DenimCo',
    images: ['https://images.unsplash.com/photo-1542272604-787c3835535d?w=500'],
    stock: 30,
    ratings: { average: 4.5, count: 42 },
    tags: ['jeans', 'slim fit', 'denim'],
    isFeatured: true
  },
  {
    name: 'Formal Shirt',
    description: 'Elegant formal shirt for office and events. Wrinkle-free fabric.',
    price: 899,
    originalPrice: 1299,
    category: 'Men',
    subcategory: 'Shirts',
    brand: 'Oxford',
    images: ['https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=500'],
    stock: 40,
    ratings: { average: 4.3, count: 18 },
    tags: ['formal', 'office', 'cotton'],
    isFeatured: false
  },
  {
    name: 'Casual Hoodie',
    description: 'Warm and cozy hoodie for winter days. Premium fleece material.',
    price: 1099,
    originalPrice: 1599,
    category: 'Men',
    subcategory: 'Hoodies',
    brand: 'StreetWear',
    images: ['https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=500'],
    stock: 35,
    ratings: { average: 4.4, count: 31 },
    tags: ['hoodie', 'winter', 'casual'],
    isFeatured: true
  },
  {
    name: 'Polo T-Shirt',
    description: 'Classic polo t-shirt for men. Perfect for casual and semi-formal occasions.',
    price: 699,
    originalPrice: 999,
    category: 'Men',
    subcategory: 'T-Shirts',
    brand: 'Lacoste',
    images: ['https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?w=500'],
    stock: 45,
    ratings: { average: 4.1, count: 22 },
    tags: ['polo', 'casual', 'classic'],
    isFeatured: false
  },
  {
    name: 'Chino Pants',
    description: 'Versatile chino pants for work or weekend. Comfortable cotton blend.',
    price: 1199,
    originalPrice: 1799,
    category: 'Men',
    subcategory: 'Pants',
    brand: 'Dockers',
    images: ['https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=500'],
    stock: 25,
    ratings: { average: 4.3, count: 28 },
    tags: ['chino', 'pants', 'formal'],
    isFeatured: false
  },
  {
    name: 'Leather Jacket',
    description: 'Premium leather jacket for men. Timeless style and durability.',
    price: 4999,
    originalPrice: 7999,
    category: 'Men',
    subcategory: 'Jackets',
    brand: 'LeatherPro',
    images: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500'],
    stock: 15,
    ratings: { average: 4.8, count: 45 },
    tags: ['leather', 'jacket', 'premium'],
    isFeatured: true
  },
  {
    name: 'Oxford Shoes',
    description: 'Classic oxford shoes for formal occasions. Genuine leather.',
    price: 2499,
    originalPrice: 3999,
    category: 'Men',
    subcategory: 'Shoes',
    brand: 'Clarks',
    images: ['https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=500'],
    stock: 20,
    ratings: { average: 4.6, count: 35 },
    tags: ['shoes', 'formal', 'oxford'],
    isFeatured: false
  },
  {
    name: 'Denim Shirt',
    description: 'Trendy denim shirt for casual outings. Button-down style.',
    price: 899,
    originalPrice: 1299,
    category: 'Men',
    subcategory: 'Shirts',
    brand: 'Levis',
    images: ['https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=500'],
    stock: 30,
    ratings: { average: 4.2, count: 19 },
    tags: ['denim', 'shirt', 'casual'],
    isFeatured: false
  },
  {
    name: 'Sports Shorts',
    description: 'Lightweight sports shorts for gym and workouts. Quick-dry fabric.',
    price: 599,
    originalPrice: 899,
    category: 'Men',
    subcategory: 'Shorts',
    brand: 'Nike',
    images: ['https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=500'],
    stock: 50,
    ratings: { average: 4.4, count: 38 },
    tags: ['shorts', 'sports', 'gym'],
    isFeatured: false
  },

  // Women Category - 10 Products
  {
    name: 'Floral Summer Dress',
    description: 'Beautiful floral print summer dress. Lightweight and perfect for warm days.',
    price: 1499,
    originalPrice: 2499,
    category: 'Women',
    subcategory: 'Dresses',
    brand: 'Bloom',
    images: ['https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=500'],
    stock: 25,
    ratings: { average: 4.7, count: 56 },
    tags: ['dress', 'floral', 'summer'],
    isFeatured: true
  },
  {
    name: 'Denim Jacket',
    description: 'Classic denim jacket for women. Versatile and stylish.',
    price: 1799,
    originalPrice: 2799,
    category: 'Women',
    subcategory: 'Jackets',
    brand: 'UrbanStyle',
    images: ['https://images.unsplash.com/photo-1551537482-f2075a1d41f2?w=500'],
    stock: 20,
    ratings: { average: 4.4, count: 32 },
    tags: ['jacket', 'denim', 'casual'],
    isFeatured: true
  },
  {
    name: 'Leather Handbag',
    description: 'Genuine leather handbag with multiple compartments. Elegant and functional.',
    price: 2499,
    originalPrice: 3999,
    category: 'Women',
    subcategory: 'Bags',
    brand: 'LuxeLeather',
    images: ['https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=500'],
    stock: 15,
    ratings: { average: 4.8, count: 67 },
    tags: ['handbag', 'leather', 'premium'],
    isFeatured: true
  },
  {
    name: 'Silk Saree',
    description: 'Elegant silk saree for traditional occasions. Rich fabric and beautiful design.',
    price: 2999,
    originalPrice: 4999,
    category: 'Women',
    subcategory: 'Sarees',
    brand: 'FabIndia',
    images: ['https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=500'],
    stock: 10,
    ratings: { average: 4.9, count: 42 },
    tags: ['saree', 'silk', 'traditional'],
    isFeatured: true
  },
  {
    name: 'High-Waist Jeans',
    description: 'Trendy high-waist jeans for women. Flattering fit with stretch.',
    price: 1399,
    originalPrice: 2199,
    category: 'Women',
    subcategory: 'Jeans',
    brand: 'Only',
    images: ['https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=500'],
    stock: 35,
    ratings: { average: 4.5, count: 48 },
    tags: ['jeans', 'high-waist', 'fashion'],
    isFeatured: false
  },
  {
    name: 'Crop Top',
    description: 'Stylish crop top for casual wear. Perfect for summer.',
    price: 599,
    originalPrice: 899,
    category: 'Women',
    subcategory: 'Tops',
    brand: 'Forever21',
    images: ['https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=500'],
    stock: 40,
    ratings: { average: 4.2, count: 25 },
    tags: ['crop top', 'summer', 'casual'],
    isFeatured: false
  },
  {
    name: 'Pencil Skirt',
    description: 'Professional pencil skirt for office wear. Elegant and comfortable.',
    price: 899,
    originalPrice: 1399,
    category: 'Women',
    subcategory: 'Skirts',
    brand: 'Zara',
    images: ['https://images.unsplash.com/photo-1577900232427-18219b9166a0?w=500'],
    stock: 25,
    ratings: { average: 4.3, count: 21 },
    tags: ['skirt', 'pencil', 'office'],
    isFeatured: false
  },
  {
    name: 'Leather Boots',
    description: 'Elegant leather boots for women. Stylish and durable.',
    price: 2799,
    originalPrice: 4499,
    category: 'Women',
    subcategory: 'Boots',
    brand: 'SteveMadden',
    images: ['https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=500'],
    stock: 15,
    ratings: { average: 4.6, count: 38 },
    tags: ['boots', 'leather', 'fashion'],
    isFeatured: true
  },
  {
    name: 'Party Wear Gown',
    description: 'Stunning party wear gown. Perfect for special occasions.',
    price: 3999,
    originalPrice: 5999,
    category: 'Women',
    subcategory: 'Dresses',
    brand: 'VeraWang',
    images: ['https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=500'],
    stock: 8,
    ratings: { average: 4.8, count: 52 },
    tags: ['gown', 'party', 'formal'],
    isFeatured: true
  },
  {
    name: 'Anarkali Suit',
    description: 'Beautiful Anarkali suit with embroidery. Traditional elegance.',
    price: 2499,
    originalPrice: 3999,
    category: 'Women',
    subcategory: 'Suits',
    brand: 'Libas',
    images: ['https://media.istockphoto.com/id/1280615423/photo/young-woman-diwali-celebrate-stock-photo.jpg?s=1024x1024&w=is&k=20&c=gzJPExxnvy6uOOLT5R0WydStGQfaDVcze4fXb4SEefY='],
    stock: 12,
    ratings: { average: 4.7, count: 35 },
    tags: ['anarkali', 'traditional', 'ethnic'],
    isFeatured: false
  },

  // Electronics Category - 10 Products
  {
    name: 'Wireless Bluetooth Headphones',
    description: 'High-quality wireless headphones with noise cancellation. 20 hours battery life.',
    price: 2499,
    originalPrice: 3999,
    category: 'Electronics',
    subcategory: 'Audio',
    brand: 'SoundMax',
    images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500'],
    stock: 35,
    ratings: { average: 4.6, count: 89 },
    tags: ['headphones', 'wireless', 'bluetooth'],
    isFeatured: true
  },
  {
    name: 'Smart Watch',
    description: 'Feature-rich smart watch with heart rate monitor, GPS, and water resistance.',
    price: 4999,
    originalPrice: 6999,
    category: 'Electronics',
    subcategory: 'Wearable',
    brand: 'TechPro',
    images: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500'],
    stock: 20,
    ratings: { average: 4.5, count: 45 },
    tags: ['smartwatch', 'fitness', 'wearable'],
    isFeatured: true
  },
  {
    name: 'Portable Speaker',
    description: 'Compact Bluetooth speaker with powerful bass. 12 hours playtime.',
    price: 1299,
    originalPrice: 1999,
    category: 'Electronics',
    subcategory: 'Audio',
    brand: 'SoundMax',
    images: ['https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=500'],
    stock: 40,
    ratings: { average: 4.3, count: 28 },
    tags: ['speaker', 'bluetooth', 'portable'],
    isFeatured: false
  },
  {
    name: 'Laptop Stand',
    description: 'Ergonomic laptop stand with adjustable height. Better posture while working.',
    price: 899,
    originalPrice: 1499,
    category: 'Electronics',
    subcategory: 'Accessories',
    brand: 'TechGear',
    images: ['https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=500'],
    stock: 50,
    ratings: { average: 4.4, count: 32 },
    tags: ['laptop', 'stand', 'office'],
    isFeatured: false
  },
  {
    name: 'Wireless Mouse',
    description: 'Ergonomic wireless mouse with precision tracking. Silent clicks.',
    price: 699,
    originalPrice: 1199,
    category: 'Electronics',
    subcategory: 'Accessories',
    brand: 'Logitech',
    images: ['https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=500'],
    stock: 60,
    ratings: { average: 4.5, count: 55 },
    tags: ['mouse', 'wireless', 'office'],
    isFeatured: false
  },
  {
    name: 'Mechanical Keyboard',
    description: 'RGB mechanical keyboard for gaming. Tactile switches and customizable keys.',
    price: 2499,
    originalPrice: 3999,
    category: 'Electronics',
    subcategory: 'Accessories',
    brand: 'Corsair',
    images: ['https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?w=500'],
    stock: 25,
    ratings: { average: 4.7, count: 68 },
    tags: ['keyboard', 'gaming', 'mechanical'],
    isFeatured: true
  },
  {
    name: 'USB Hub',
    description: '7-port USB hub for all your devices. Fast data transfer.',
    price: 499,
    originalPrice: 799,
    category: 'Electronics',
    subcategory: 'Accessories',
    brand: 'Anker',
    images: ['https://images.unsplash.com/photo-1625723044792-44de16ccb4e9?w=500'],
    stock: 70,
    ratings: { average: 4.3, count: 42 },
    tags: ['usb', 'hub', 'accessories'],
    isFeatured: false
  },
  {
    name: 'Webcam HD',
    description: '1080p HD webcam for video calls and streaming. Built-in microphone.',
    price: 1799,
    originalPrice: 2999,
    category: 'Electronics',
    subcategory: 'Camera',
    brand: 'Logitech',
    images: ['https://images.unsplash.com/photo-1587826080692-f439cd0b70da?w=500'],
    stock: 20,
    ratings: { average: 4.6, count: 38 },
    tags: ['webcam', 'hd', 'streaming'],
    isFeatured: false
  },
  {
    name: 'Power Bank 20000mAh',
    description: 'High-capacity power bank with fast charging. Charge multiple devices.',
    price: 1199,
    originalPrice: 1999,
    category: 'Electronics',
    subcategory: 'Accessories',
    brand: 'Xiaomi',
    images: ['https://images.unsplash.com/photo-1566654108875-2bedef4ac60e?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
    stock: 45,
    ratings: { average: 4.4, count: 52 },
    tags: ['power bank', 'charging', 'portable'],
    isFeatured: false
  },
  {
    name: 'Wireless Charger',
    description: 'Fast wireless charging pad for smartphones. Sleek design.',
    price: 799,
    originalPrice: 1299,
    category: 'Electronics',
    subcategory: 'Accessories',
    brand: 'Samsung',
    images: ['https://plus.unsplash.com/premium_photo-1661481079679-04e8a19e258c?q=80&w=1460&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
    stock: 35,
    ratings: { average: 4.2, count: 25 },
    tags: ['charger', 'wireless', 'fast charging'],
    isFeatured: false
  },

  // Accessories Category - 10 Products
  {
    name: 'Sunglasses',
    description: 'UV protection sunglasses with polarized lenses. Stylish and functional.',
    price: 899,
    originalPrice: 1499,
    category: 'Accessories',
    subcategory: 'Eyewear',
    brand: 'SunStyle',
    images: ['https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=500'],
    stock: 50,
    ratings: { average: 4.1, count: 22 },
    tags: ['sunglasses', 'polarized', 'summer'],
    isFeatured: false
  },
  {
    name: 'Leather Belt',
    description: 'Genuine leather belt with classic buckle. Durable and elegant.',
    price: 599,
    originalPrice: 999,
    category: 'Accessories',
    subcategory: 'Belts',
    brand: 'LeatherCraft',
    images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500'],
    stock: 45,
    ratings: { average: 4.4, count: 35 },
    tags: ['belt', 'leather', 'formal'],
    isFeatured: false
  },
  {
    name: 'Silver Watch',
    description: 'Elegant silver watch for men. Classic design with quartz movement.',
    price: 2499,
    originalPrice: 3999,
    category: 'Accessories',
    subcategory: 'Watches',
    brand: 'Titan',
    images: ['https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=500'],
    stock: 20,
    ratings: { average: 4.5, count: 40 },
    tags: ['watch', 'silver', 'classic'],
    isFeatured: true
  },
  {
    name: 'Gold Earrings',
    description: 'Beautiful gold plated earrings. Perfect for parties and events.',
    price: 799,
    originalPrice: 1299,
    category: 'Accessories',
    subcategory: 'Jewelry',
    brand: 'Kalyan',
    images: ['https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=500'],
    stock: 35,
    ratings: { average: 4.3, count: 28 },
    tags: ['earrings', 'gold', 'jewelry'],
    isFeatured: false
  },
  {
    name: 'Leather Wallet',
    description: 'Genuine leather wallet with multiple card slots. Slim design.',
    price: 699,
    originalPrice: 1099,
    category: 'Accessories',
    subcategory: 'Wallets',
    brand: 'Levis',
    images: ['https://images.unsplash.com/photo-1627123424574-724758594e93?w=500'],
    stock: 40,
    ratings: { average: 4.2, count: 32 },
    tags: ['wallet', 'leather', 'casual'],
    isFeatured: false
  },
  {
    name: 'Silk Scarf',
    description: 'Elegant silk scarf with floral print. Versatile accessory.',
    price: 899,
    originalPrice: 1499,
    category: 'Accessories',
    subcategory: 'Scarves',
    brand: 'Hermes',
    images: ['https://media.istockphoto.com/id/1146273598/photo/young-woman-shopping-for-a-new-scarf-and-choosing-colorful-fabric-in-bazar.jpg?s=1024x1024&w=is&k=20&c=1QElWlFuPeG5uSvJ1l_aoT6CdPHSyNMAY9bjCLMPdD0='],
    stock: 25,
    ratings: { average: 4.6, count: 22 },
    tags: ['scarf', 'silk', 'fashion'],
    isFeatured: false
  },
  {
    name: 'Baseball Cap',
    description: 'Stylish baseball cap with adjustable strap. Perfect for casual wear.',
    price: 399,
    originalPrice: 699,
    category: 'Accessories',
    subcategory: 'Hats',
    brand: 'Adidas',
    images: ['https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=500'],
    stock: 50,
    ratings: { average: 4.1, count: 18 },
    tags: ['cap', 'baseball', 'casual'],
    isFeatured: false
  },
  {
    name: 'Leather Gloves',
    description: 'Premium leather gloves for winter. Warm and stylish.',
    price: 1099,
    originalPrice: 1799,
    category: 'Accessories',
    subcategory: 'Gloves',
    brand: 'Decathlon',
    images: ['https://images.unsplash.com/photo-1643650374762-196c86358df3?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
    stock: 20,
    ratings: { average: 4.4, count: 15 },
    tags: ['gloves', 'leather', 'winter'],
    isFeatured: false
  },
  {
    name: 'Sunglasses for Women',
    description: 'Trendy sunglasses for women. UV protection and stylish design.',
    price: 799,
    originalPrice: 1299,
    category: 'Accessories',
    subcategory: 'Eyewear',
    brand: 'RayBan',
    images: ['https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=500'],
    stock: 35,
    ratings: { average: 4.5, count: 30 },
    tags: ['sunglasses', 'women', 'fashion'],
    isFeatured: true
  },
  {
    name: 'Diamond Pendant',
    description: 'Elegant diamond pendant necklace. Perfect for special occasions.',
    price: 5999,
    originalPrice: 9999,
    category: 'Accessories',
    subcategory: 'Jewelry',
    brand: 'Tanishq',
    images: ['https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500'],
    stock: 5,
    ratings: { average: 4.9, count: 18 },
    tags: ['pendant', 'diamond', 'jewelry'],
    isFeatured: true
  },

  // Footwear Category - 10 Products
  {
    name: 'Running Shoes',
    description: 'Lightweight running shoes with cushioned sole. Perfect for workouts.',
    price: 2499,
    originalPrice: 3999,
    category: 'Footwear',
    subcategory: 'Sports',
    brand: 'SportX',
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500'],
    stock: 30,
    ratings: { average: 4.7, count: 72 },
    tags: ['shoes', 'running', 'sports'],
    isFeatured: true
  },
  {
    name: 'Casual Sneakers',
    description: 'Comfortable casual sneakers for everyday wear. Trendy design.',
    price: 1799,
    originalPrice: 2799,
    category: 'Footwear',
    subcategory: 'Sneakers',
    brand: 'StreetStyle',
    images: ['https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=500'],
    stock: 35,
    ratings: { average: 4.3, count: 41 },
    tags: ['sneakers', 'casual', 'comfort'],
    isFeatured: false
  },
  {
    name: 'Formal Leather Shoes',
    description: 'Premium leather formal shoes for office. Classic style.',
    price: 2999,
    originalPrice: 4499,
    category: 'Footwear',
    subcategory: 'Formal',
    brand: 'Bata',
    images: ['https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=500'],
    stock: 25,
    ratings: { average: 4.5, count: 38 },
    tags: ['shoes', 'formal', 'leather'],
    isFeatured: false
  },
  {
    name: 'Sports Sandals',
    description: 'Comfortable sports sandals with adjustable straps. Perfect for summer.',
    price: 999,
    originalPrice: 1599,
    category: 'Footwear',
    subcategory: 'Sandals',
    brand: 'Crocs',
    images: ['https://images.unsplash.com/photo-1603487742131-4160ec999306?w=500'],
    stock: 40,
    ratings: { average: 4.2, count: 25 },
    tags: ['sandals', 'sports', 'summer'],
    isFeatured: false
  },
  {
    name: 'Canvas Shoes',
    description: 'Classic canvas shoes for casual wear. Lightweight and breathable.',
    price: 799,
    originalPrice: 1299,
    category: 'Footwear',
    subcategory: 'Casual',
    brand: 'Converse',
    images: ['https://images.unsplash.com/photo-1463100099107-aa0980c362e6?w=500'],
    stock: 45,
    ratings: { average: 4.4, count: 52 },
    tags: ['canvas', 'shoes', 'casual'],
    isFeatured: false
  },
  {
    name: 'Heels for Women',
    description: 'Elegant high heels for women. Perfect for parties and office.',
    price: 1899,
    originalPrice: 2999,
    category: 'Footwear',
    subcategory: 'Heels',
    brand: 'Liberty',
    images: ['https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=500'],
    stock: 20,
    ratings: { average: 4.3, count: 28 },
    tags: ['heels', 'women', 'formal'],
    isFeatured: false
  },
  {
    name: 'Loafers',
    description: 'Classic leather loafers for men. Comfortable slip-on design.',
    price: 2199,
    originalPrice: 3499,
    category: 'Footwear',
    subcategory: 'Loafers',
    brand: 'HushPuppies',
    images: ['https://images.unsplash.com/photo-1614252369475-531eba835eb1?w=500'],
    stock: 25,
    ratings: { average: 4.6, count: 42 },
    tags: ['loafers', 'leather', 'formal'],
    isFeatured: false
  },
  {
    name: 'Flip Flops',
    description: 'Comfortable flip flops for beach and home. Lightweight.',
    price: 299,
    originalPrice: 499,
    category: 'Footwear',
    subcategory: 'Flip Flops',
    brand: 'Reef',
    images: ['https://images.unsplash.com/photo-1603487742131-4160ec999306?w=500'],
    stock: 60,
    ratings: { average: 4.0, count: 35 },
    tags: ['flip flops', 'beach', 'summer'],
    isFeatured: false
  },
  {
    name: 'Boots for Men',
    description: 'Stylish boots for men. Perfect for winter and casual wear.',
    price: 2499,
    originalPrice: 3999,
    category: 'Footwear',
    subcategory: 'Boots',
    brand: 'RedChief',
    images: ['https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=500'],
    stock: 15,
    ratings: { average: 4.5, count: 25 },
    tags: ['boots', 'men', 'winter'],
    isFeatured: false
  },
  {
    name: 'Ballet Flats',
    description: 'Comfortable ballet flats for women. Elegant and lightweight.',
    price: 899,
    originalPrice: 1499,
    category: 'Footwear',
    subcategory: 'Flats',
    brand: 'Catwalk',
    images: ['https://images.unsplash.com/photo-1560343090-f0409e92791a?w=500'],
    stock: 30,
    ratings: { average: 4.2, count: 18 },
    tags: ['flats', 'women', 'ballet'],
    isFeatured: false
  },

  // Home Category - 10 Products
  {
    name: 'Decorative Wall Clock',
    description: 'Modern wall clock with silent movement. Perfect for home decor.',
    price: 799,
    originalPrice: 1299,
    category: 'Home',
    subcategory: 'Decor',
    brand: 'HomeStyle',
    images: ['https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?w=500'],
    stock: 25,
    ratings: { average: 4.2, count: 18 },
    tags: ['clock', 'wall', 'decor'],
    isFeatured: false
  },
  {
    name: 'Table Lamp',
    description: 'Elegant table lamp with warm lighting. Adds ambiance to any room.',
    price: 1199,
    originalPrice: 1999,
    category: 'Home',
    subcategory: 'Lighting',
    brand: 'Lumiere',
    images: ['https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=500'],
    stock: 20,
    ratings: { average: 4.5, count: 29 },
    tags: ['lamp', 'table', 'lighting'],
    isFeatured: true
  },
  {
    name: 'Throw Pillows Set',
    description: 'Set of 4 decorative throw pillows. Soft and comfortable.',
    price: 899,
    originalPrice: 1499,
    category: 'Home',
    subcategory: 'Cushions',
    brand: 'IKEA',
    images: ['https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=500'],
    stock: 40,
    ratings: { average: 4.3, count: 35 },
    tags: ['pillows', 'decor', 'cushions'],
    isFeatured: false
  },
  {
    name: 'Wall Mirror',
    description: 'Elegant wall mirror with decorative frame. Makes room look bigger.',
    price: 1499,
    originalPrice: 2499,
    category: 'Home',
    subcategory: 'Decor',
    brand: 'HomeCenter',
    images: ['https://images.unsplash.com/photo-1618220179428-22790b461013?w=500'],
    stock: 15,
    ratings: { average: 4.4, count: 22 },
    tags: ['mirror', 'wall', 'decor'],
    isFeatured: false
  },
  {
    name: 'Bed Sheet Set',
    description: 'Premium cotton bed sheet set. Soft and comfortable.',
    price: 1299,
    originalPrice: 2199,
    category: 'Home',
    subcategory: 'Bedding',
    brand: 'SleepWell',
    images: ['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=500'],
    stock: 30,
    ratings: { average: 4.6, count: 45 },
    tags: ['bedsheet', 'cotton', 'bedding'],
    isFeatured: true
  },
  {
    name: 'Curtain Set',
    description: 'Elegant curtain set for living room. Light-blocking fabric.',
    price: 1799,
    originalPrice: 2999,
    category: 'Home',
    subcategory: 'Curtains',
    brand: 'ComfortZone',
    images: ['https://images.unsplash.com/photo-1513694203232-719a280e022f?w=500'],
    stock: 20,
    ratings: { average: 4.3, count: 18 },
    tags: ['curtains', 'window', 'decor'],
    isFeatured: false
  },
  {
    name: 'Photo Frame Set',
    description: 'Set of 5 decorative photo frames. Perfect for home decor.',
    price: 599,
    originalPrice: 999,
    category: 'Home',
    subcategory: 'Decor',
    brand: 'HomeStyle',
    images: ['https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=500'],
    stock: 35,
    ratings: { average: 4.1, count: 15 },
    tags: ['frame', 'photo', 'decor'],
    isFeatured: false
  },
  {
    name: 'Floor Rug',
    description: 'Soft floor rug for living room. Adds warmth to your home.',
    price: 2199,
    originalPrice: 3499,
    category: 'Home',
    subcategory: 'Rugs',
    brand: 'FabRugs',
    images: ['https://images.unsplash.com/photo-1531835551805-16d864c8d311?w=500'],
    stock: 15,
    ratings: { average: 4.5, count: 28 },
    tags: ['rug', 'floor', 'living room'],
    isFeatured: false
  },
  {
    name: 'Vase Set',
    description: 'Beautiful ceramic vase set. Perfect for flower arrangements.',
    price: 799,
    originalPrice: 1299,
    category: 'Home',
    subcategory: 'Decor',
    brand: 'CraftHome',
    images: ['https://images.unsplash.com/photo-1578500494198-246f612d3b3d?w=500'],
    stock: 25,
    ratings: { average: 4.4, count: 20 },
    tags: ['vase', 'ceramic', 'decor'],
    isFeatured: false
  },
  {
    name: 'Wall Shelf',
    description: 'Modern wall shelf for books and decor. Easy to install.',
    price: 999,
    originalPrice: 1699,
    category: 'Home',
    subcategory: 'Storage',
    brand: 'IKEA',
    images: ['https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=500'],
    stock: 20,
    ratings: { average: 4.2, count: 22 },
    tags: ['shelf', 'wall', 'storage'],
    isFeatured: false
  },

  // Sports Category - 10 Products
  {
    name: 'Yoga Mat',
    description: 'Non-slip yoga mat with carrying strap. Eco-friendly material.',
    price: 599,
    originalPrice: 999,
    category: 'Sports',
    subcategory: 'Yoga',
    brand: 'ZenFit',
    images: ['https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=500'],
    stock: 40,
    ratings: { average: 4.6, count: 52 },
    tags: ['yoga', 'mat', 'fitness'],
    isFeatured: false
  },
  {
    name: 'Sports Water Bottle',
    description: 'Insulated water bottle. Keeps drinks cold for 24 hours.',
    price: 449,
    originalPrice: 799,
    category: 'Sports',
    subcategory: 'Accessories',
    brand: 'HydroMax',
    images: ['https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=500'],
    stock: 60,
    ratings: { average: 4.3, count: 38 },
    tags: ['bottle', 'water', 'sports'],
    isFeatured: false
  },
  {
    name: 'Cricket Bat',
    description: 'Willow cricket bat for professional players. Lightweight and durable.',
    price: 1999,
    originalPrice: 2999,
    category: 'Sports',
    subcategory: 'Cricket',
    brand: 'SG',
    images: ['https://plus.unsplash.com/premium_photo-1679917424562-c0647ab694d1?q=80&w=735&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
    stock: 15,
    ratings: { average: 4.7, count: 32 },
    tags: ['cricket', 'bat', 'sports'],
    isFeatured: false
  },
  {
    name: 'Football',
    description: 'Professional football for matches. Durable synthetic leather.',
    price: 899,
    originalPrice: 1499,
    category: 'Sports',
    subcategory: 'Football',
    brand: 'Nike',
    images: ['https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=500'],
    stock: 30,
    ratings: { average: 4.5, count: 45 },
    tags: ['football', 'sports', 'match'],
    isFeatured: true
  },
  {
    name: 'Badminton Racket',
    description: 'Professional badminton racket with carbon fiber. Lightweight.',
    price: 1499,
    originalPrice: 2499,
    category: 'Sports',
    subcategory: 'Badminton',
    brand: 'Yonex',
    images: ['https://images.unsplash.com/photo-1708312604109-16c0be9326cd?q=80&w=1074&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
    stock: 25,
    ratings: { average: 4.6, count: 38 },
    tags: ['badminton', 'racket', 'sports'],
    isFeatured: false
  },
  {
    name: 'Basketball',
    description: 'Indoor/Outdoor basketball. Excellent grip and durability.',
    price: 799,
    originalPrice: 1299,
    category: 'Sports',
    subcategory: 'Basketball',
    brand: 'Spalding',
    images: ['https://plus.unsplash.com/premium_photo-1673457998696-3f26a401c301?q=80&w=753&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
    stock: 20,
    ratings: { average: 4.4, count: 28 },
    tags: ['basketball', 'sports', 'indoor'],
    isFeatured: false
  },
  {
    name: 'Tennis Racket',
    description: 'Professional tennis racket with graphite frame. Perfect for beginners.',
    price: 2499,
    originalPrice: 3999,
    category: 'Sports',
    subcategory: 'Tennis',
    brand: 'Wilson',
    images: ['https://plus.unsplash.com/premium_photo-1707423389050-6a38a78a7597?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
    stock: 10,
    ratings: { average: 4.7, count: 22 },
    tags: ['tennis', 'racket', 'sports'],
    isFeatured: false
  },
  {
    name: 'Gym Bag',
    description: 'Spacious gym bag with multiple compartments. Durable material.',
    price: 899,
    originalPrice: 1499,
    category: 'Sports',
    subcategory: 'Accessories',
    brand: 'Puma',
    images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500'],
    stock: 35,
    ratings: { average: 4.3, count: 42 },
    tags: ['gym', 'bag', 'sports'],
    isFeatured: false
  },
  {
    name: 'Jump Rope',
    description: 'Adjustable speed jump rope for workout. Anti-slip handles.',
    price: 299,
    originalPrice: 499,
    category: 'Sports',
    subcategory: 'Fitness',
    brand: 'Fitbit',
    images: ['https://images.unsplash.com/photo-1594381898411-846e7d193883?w=500'],
    stock: 50,
    ratings: { average: 4.2, count: 35 },
    tags: ['jump rope', 'fitness', 'workout'],
    isFeatured: false
  },
  {
    name: 'Resistance Bands Set',
    description: 'Set of 5 resistance bands for strength training. Different tension levels.',
    price: 699,
    originalPrice: 1199,
    category: 'Sports',
    subcategory: 'Fitness',
    brand: 'FitSimplify',
    images: ['https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=500'],
    stock: 45,
    ratings: { average: 4.4, count: 52 },
    tags: ['resistance bands', 'fitness', 'strength'],
    isFeatured: false
  }
];

async function seed() {
  try {
    const MONGO_URI = process.env.MONGO_URI || 'mongodb://localhost:27017/ecommerce';
    await mongoose.connect(MONGO_URI);
    console.log('Connected to MongoDB');

    // Clear existing products
    await Product.deleteMany({});
    console.log('Cleared existing products');

    // Insert new products
    await Product.insertMany(sampleProducts);
    console.log('Inserted 70 sample products (10 per category: Men, Women, Electronics, Accessories, Footwear, Home, Sports)');

    // Create admin user
    const adminExists = await User.findOne({ email: 'admin@ecommerce.com' });
    if (!adminExists) {
      await User.create({
        name: 'Admin User',
        email: 'admin@ecommerce.com',
        password: 'admin123',
        role: 'admin'
      });
      console.log('Created admin user (admin@ecommerce.com / admin123)');
    }

    console.log('Seed completed successfully!');
    process.exit(0);
  } catch (error) {
    console.error('Seed error:', error);
    process.exit(1);
  }
}

seed();